[gmail]
client_id = "751867316045-sapf6h289jt7h6kq03i160tb3u929vvt.apps.googleusercontent.com"
client_secret = "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"
refresh_token = "1//0hC22_w1pSXqoCgYIARAAGBESNwF-L9IrqcAhjVI7C_41RPJKX4oP3uM6PHPLXpy1OanKgCtkNHuV8OoUayg46UfWn0VJIC-nBnY"

[laudite]
client_id = "1060780935338-ntjfodiv11f72vt9jeq6ivn0s2h6maan.apps.googleusercontent.com"
client_secret = "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"
refresh_token = "1//0hSovg0n30WQTCgYIARAAGBESNwF-L9IrOwNIO_TaeD0OI1g4nZLbYPta89ivhiygewS3JsTd7DJ0tmLtFbHOIeumQQcy7h9O2k4"

[ics]
url = "https://outlook.office365.com/owa/calendar/7dc03ffb51384f9ca501870ee3774770@arlequim.com/7aae8a96208a43ceb50db643aae6155e12716450029896530134/calendar.ics"
