[gmail]
client_id = "..."
client_secret = "..."
refresh_token = "..."

[laudite]
client_id = "..."
client_secret = "..."
refresh_token = "..."

[ics]
url = "https://outlook.office365.com/owa/calendar/..."
